language: c
sudo: false

env:
  global:
   - TFTPDIR=~/images/

script:
  - mkdir -p ~/images/
  - make netbox_app_zero_defconfig
  - make
  - make clean
  - make netbox_app_coronet_defconfig
  - make
  - make clean
  - make netbox_app_dagger_defconfig
  - make
  - ls -l ~/images
  - file ~/images/*
