language: c
sudo: false

env:
  global:
   - TFTPDIR=~/images/

script:
  - mkdir -p ~/images/
  - make netbox_app_coronet_defconfig
  - make
  - make netbox_app_dagger_defconfig
  - make
  - make netbox_app_zero_defconfig
  - make || cat output/build/libite-2.2.0/config.log
  - ls -l ~/images
  - file ~/images/*
