name: NetBox App image artifacts

on:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [coronet, dagger, zero]
    steps:
      - uses: actions/checkout@v2
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          key: dl
          path: dl
      - name: defconfig
        run: make netbox_app_${{ matrix.platform }}_defconfig
      - name: build
        run: make
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: netbox-app-${{ matrix.platform }}
          path: output/images/*
