name: Release General

on:
  push:
    tags:
      - '[0-9]*.*'

jobs:
  release:
    name: Create GitHub release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Variables
        id: vars
        run: |
          ver=${GITHUB_REF#refs/tags/}
          if echo $ver | grep -qE '[0-9.]+(-alpha|-beta|-rc)[0-9]*'; then
            echo ::set-output name=pre::true
          else
            echo ::set-output name=pre::false
          fi
      - name: Create release ...
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NetBox ${{ github.ref }}
          draft: false
          prerelease: ${{ steps.vars.outputs.pre }}
  build:
    name: Build ${{ matrix.profile }} for ${{ matrix.platform }} platform
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [app, os]
        platform: [basis, coronet, dagger, envoy, zero]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set Build Variables
        id: vars
        run: |
          export NB_TUPLE=${{ matrix.profile }}-${{ matrix.platform }}
          export NB_VER=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag::${NB_VER}
          echo ::set-output name=dir::netbox-${NB_TUPLE}-${NB_VER}
          echo ::set-output name=tgz::netbox-${NB_TUPLE}-${NB_VER}.tar.gz
      - uses: actions/cache@v2
        with:
          path: dl/
          key: dl-${{ matrix.platform }}-${{ matrix.profile }}-${{ hashFiles('.git/modules/netbox/HEAD', 'configs/*', 'package/*/*.hash') }}
          restore-keys: |
            dl-${{ matrix.platform }}-${{ matrix.profile }}-
            dl-${{ matrix.platform }}-
            dl-
      - name: Configure & Build
        env:
          RELEASE: ${{ steps.vars.outputs.tag }}
        run: |
          echo "Building NetBox ${{ steps.vars.outputs.tgz }} ..."
          make netbox_${{ matrix.profile }}_${{ matrix.platform }}_defconfig
          make
          cd output
          mv images ${{ steps.vars.outputs.dir }}
          tar cfz ${{ steps.vars.outputs.tgz }} ${{ steps.vars.outputs.dir }}
          ls *
      - name: Upload release artifacts ...
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.release.outputs.release_id }}
          args: output/${{ steps.vars.outputs.tgz }}
